### ISSUE TITLE
How do we test functions from executables ?

### ISSUE THREAD

**Issue by atodorov** [hspec/hspec-example#12] opened 2017-05-26 14:33 UTC
In the project I'm working on there are these files:

```
RPM/...
       + various modules here
rpm2json.hs
inspect.hs
tests/...
        Spec.hs
        RPM/VersionSpec.hs
                ... etc ..
```

In `rpm2json.hs` there are several helper functions (some do IO others don't). How can I write tests for them ?

I've tried adding a `tests/rpm2jsonSpec.hs` and trying to import one of the functions but doesn't seem to work. My test suite doesn't detect the new examples ?

UPDATE: is what I'm asking possible to do or I have to move all of my functions into a helper module and test that and only call Helper.main inside the executable ?

Thanks

**Comment by sol** [comment] 2017-05-26 23:45
> UPDATE: is what I'm asking possible to do or I have to move all of my functions into a helper module and test that and only call Helper.main inside the executable ?

@atodorov I'm assuming `rpm2json.hs` contains your `Main` module.  If that is the case, then yes, you have to move your functions into a helper module.  Importing stuff from `Main` in a test suite is not possible.

You can take a look at https://github.com/sol/hpack for how I organize my tests in a situation like this.  Specifically, look at:

 - https://github.com/sol/hpack/blob/master/driver/Main.hs
 - https://github.com/sol/hpack/blob/master/src/Hpack.hs
 - https://github.com/sol/hpack/blob/master/test/HpackSpec.hs

**Comment by sol** [comment] 2017-05-26 23:46
Hope that helps!

Closing.

**Closed by sol** 2017-05-26 23:46 UTC

**Comment by przemo-hemmersbach** [comment] 2020-08-02 09:17
Does this mean that only Modules added to "other-modules" of "library" stanza are testable in test stanza?

**Comment by Pieter-JanLavaerts** [comment] 2024-12-02 20:05
Why can hspec not test from the Main module? Is this by design? 
So with all toy projects I have to create a little module and a separate main that prints stuff?

**Comment by sol** [comment] 2024-12-03 00:28
One high school program can only have one `Main` module. Your test driver needs a `Main` module as an entry point, for that reason you can't import functions from any other `Main` module, because of that point you would have two `Main` modules. That's not possible with (ghc) Haskell.
